# Multiple regression for wineQuality -red dataset

In [1]:
#import requried lib
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn 

In [3]:
data =pd.read_csv('winequality-red.csv')
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
data.shape

(1599, 12)

In [5]:
x= data.iloc[:,:-2]
x.head(2)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70          0.0             1.9      0.076   
1            7.8              0.88          0.0             2.6      0.098   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  
0                 11.0                  34.0   0.9978  3.51       0.56  
1                 25.0                  67.0   0.9968  3.20       0.68

In [6]:
y=data.iloc[:,-2:-1]
y.head(2)

alcohol
0      9.4
1      9.8

In [9]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest =train_test_split(x,y,test_size=0.2,random_state =2)

In [12]:
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
#Train the data
print('Training started............\n')
print()
lin_reg.fit(xtrain,ytrain)
print()
print('Training complete........\n')
print()
#test the data
print('Testing invoked......\n')
ypred = lin_reg.predict(xtest)
print('Predicted Total Payment\n',ypred)
print(' \n Testing is also completed....\n')

Training started............



Training complete........


Testing invoked......

Predicted Total Payment
 [[10.50763889]
 [11.26278363]
 [10.55649739]
 [ 9.31091903]
 [ 9.87531621]
 [10.99529635]
 [11.33595764]
 [ 9.69554984]
 [ 9.97912756]
 [ 9.82149023]
 [11.26674998]
 [11.73049784]
 [ 9.88603759]
 [11.95018394]
 [ 9.77524339]
 [11.19536576]
 [10.40250374]
 [10.92193031]
 [10.54072349]
 [ 9.91308437]
 [10.50570761]
 [10.05043908]
 [10.31674846]
 [13.3185152 ]
 [ 9.75485862]
 [11.62509747]
 [ 8.73782562]
 [11.85076602]
 [10.67730724]
 [ 9.618922  ]
 [ 9.84358231]
 [10.0532664 ]
 [12.25716761]
 [11.64778461]
 [11.54748875]
 [ 9.81882219]
 [11.88754315]
 [11.03193104]
 [10.31405619]
 [10.62957865]
 [10.56311406]
 [12.38531622]
 [ 9.97663231]
 [ 9.92785249]
 [ 9.11924787]
 [11.89330535]
 [10.04504846]
 [11.58257725]
 [10.6101822 ]
 [ 9.33648435]
 [ 9.71408574]
 [ 9.93117866]
 [ 9.50272566]
 [10.44841675]
 [10.69450559]
 [ 9.17835466]
 [10.63842016]
 [ 9.0461324 ]
 [ 9.76785975]
 [10.18

In [13]:
 #Simpole Linear regression for the entire dataset (for comparision)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
base_reg = LinearRegression()
base_reg.fit(x,y)
print("Cofficient:  ",base_reg.coef_)
print()
print('Intercept:\t',base_reg.intercept_)
print()
print('R-square:\t',r2_score(ytest,ypred))

Cofficient:   [[ 5.32433095e-01  3.60837746e-01  8.30627496e-01  2.84410582e-01
  -1.46195934e+00 -2.14330209e-03 -2.29579410e-03 -6.17384805e+02
   3.76229342e+00  1.24679232e+00]]

Intercept:	 [607.22260952]

R-square:	 0.6803433884608363


# Polynomial Regression

In [32]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_features = PolynomialFeatures(degree= 2)
x_poly = poly_features.fit_transform(x)
y_poly = poly_features.fit_transform(y)

In [33]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest =train_test_split(x_poly,y_poly,test_size=0.2,random_state =2)

In [34]:
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
#Train the data
print('Training started............\n')
print()
lin_reg.fit(xtrain,ytrain)
print()
print('Training complete........\n')
print()
#test the data
print('Testing invoked......\n')
ypred = lin_reg.predict(xtest)
print('Predicted Total Payment\n',ypred)
print(' \n Testing is also completed....\n')

Training started............



Training complete........


Testing invoked......

Predicted Total Payment
 [[  1.          10.64401386 114.14392746]
 [  1.          10.66038122 114.89567224]
 [  1.          10.39003411 108.94763008]
 [  1.           9.58942709  92.31686854]
 [  1.           9.69920955  94.35858081]
 [  1.          10.94609427 120.83073264]
 [  1.          10.8655754  118.43567123]
 [  1.           9.49806131  89.76358292]
 [  1.           9.87938435  97.88880347]
 [  1.           9.24739039  84.40333254]
 [  1.          11.46070254 132.2030468 ]
 [  1.          11.47120212 132.83916559]
 [  1.           9.70052524  94.46269267]
 [  1.          12.03249419 144.81184316]
 [  1.           9.60791563  92.36080179]
 [  1.          11.29666843 128.16069067]
 [  1.          10.32998565 107.35603053]
 [  1.          10.83539626 118.1915431 ]
 [  1.          10.54164125 111.41661244]
 [  1.           9.96310492  99.35924125]
 [  1.          10.37978498 108.3335613 ]
 [  1.    

In [35]:


#call l;inear regression and agign to poly_reg variable
poly_reg=LinearRegression()
poly_reg.fit(x_poly,y)
print("Cofficient:  ",poly_reg.coef_)
print()
print('Intercept:\t',poly_reg.intercept_)
print()
print('R-square:\t',r2_score(ytest,ypred))

Cofficient:   [[ 5.25364358e-04  1.14561981e+01 -2.36085241e+02 -6.12678303e+01
   2.37522842e+01  2.61651042e+02 -4.61530732e+00  4.95799620e-02
  -7.36130677e+04  2.40224709e+02  1.70200860e+02 -1.08622884e-02
   4.06993764e-01 -6.35683683e-02  5.67833873e-02  7.48518397e-02
  -6.64249584e-03  7.65682717e-04 -1.17274473e+01  1.81047371e-01
   3.90887988e-02 -7.71185645e-01 -1.10081083e+00 -4.16677488e-01
  -5.25372585e+00  1.81783885e-02 -3.85998050e-03  2.27863544e+02
   2.35364584e+00  8.92786128e-01  1.56954085e+00 -6.39209025e-02
  -6.01520714e+00  1.47287449e-02 -1.19574712e-02  6.55901703e+01
  -9.09983545e-01  1.36249218e+00 -3.13797950e-02  8.92560708e-01
  -1.85264235e-03  6.30757540e-05 -2.53600024e+01  5.97921080e-01
  -1.64698767e-01 -1.30285949e+00  6.97451782e-03 -2.87435829e-02
  -2.40662314e+02 -5.58715050e+00 -8.70206212e-01  3.88731347e-04
  -2.94892647e-04  4.77779924e+00 -3.11116791e-02  4.99557584e-03
   3.55678285e-05 -5.13186154e-02 -2.18821433e-03  1.24730597e